nome : Pipeline CI/CD

em :
  empurrar :
    filiais :
      - principal

empregos :
  construir :
    executado : ubuntu-mais recente

    etapas :
      - nome : código de checkout
        usa : ações/checkout@v2.1.0

      - nome : Copiar arquivos
        executar : |
          COPY ./index.html /usr/share/nginx/html
          COPY ./javascript.js /usr/share/nginx/html
          COPY ./README.md /usr/share/nginx/html
          COPY ./style.css /usr/share/nginx/html

      - nome : Faça login no Docker
        usa : docker/login-action@v2.1.0
        com :
          nome de usuário : ${{ secrets.DOCKERHUB_USERNAME }}
          senha : ${{ secrets.DOCKERHUB_PASS }}

      - nome : Construir e enviar imagem Docker
        usa : docker/build-push-action@v2
        com :
          contexto : .
          empurrar : verdadeiro
          tags : geraldodevops/devopsv5:mais recentes

