name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0

      - name: Login to Docker
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.USERN }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: geraldodevops/teste:latest
