name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
    
    - name: Copy files to Docker image
      run: |
        
        docker cp ./index.html temp-container:/usr/share/nginx/html
        docker cp ./javascript.js temp-container:/usr/share/nginx/html
        docker cp ./style.css temp-container:/usr/share/nginx/html
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Push Docker image to Docker Hub
      run: docker push geraldodevops/devopsv6:latest
        
        context: 
        push: true
        tags: geraldodevops/devopsv5:latest
      
